name: una_digital_provinsi
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  get_storage: ^2.1.1
  intl: ^0.20.2
  logger: ^2.6.2
  uuid: ^4.5.2
  image_picker: ^1.2.1
  change_app_package_name: ^1.5.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  multi_select_flutter: ^4.1.3
  excel: ^4.0.6
  file_picker: ^10.3.7
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/webp/
    - assets/lotties/
    - assets/png/
    - assets/svg/
    # - .env